### ISSUE TITLE
Preview of InGOS atmospheric N2O data from 4 stations results in error: maximum call stack size exceeded

### ISSUE THREAD

**Issue by eee-ea** [ICOS-Carbon-Portal/data#30] opened 2018-11-01 08:29 UTC
URL that demonstrates this behaviour: 
https://data.icos-cp.eu/portal/#%7B%22route%22%3A%22preview%22%2C%22preview%22%3A%5B%227ru0_ALcGjD4najWW2lvaKhB%22%2C%22Yau2_5Q16eUMpeazDRSgq6KO%22%2C%22l9koXf1n_k1HpozYD99VY6M-%22%2C%22vnOa8Xjo75WZBvrE2wbDvrwv%22%5D%7D

Works correct in Firefox Quantum, not in Chrome on Windows 10. When called a second time in Chrome after a first attempt it displays: This type of preview is not implemented.

**Comment by mirzov** [comment] 2019-01-21 12:06
Is a duplicate of (later-reported) issue #33 , which has already been fixed by now.

**Closed by mirzov** 2019-01-21 12:06 UTC
